apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: customers-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: customers-app-deployment
    spec:
      containers:
        - name: customers-app-container
          image: rso6315/customers-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_SERVER_BASE-URL
              value: http://35.246.208.18/customers-service
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: third-cluster
            - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://customers-db.e-store:5432/customers
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customers-pass
                  key: POSTGRES_PASSWORD
            - name: KC_AUTH_CLIENT-SECRET
              valueFrom:
                secretKeyRef:
                  name: customers-pass
                  key: KC_AUTH_CLIENT-SECRET
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31010
      targetPort: 8080
      protocol: TCP
      name: server
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: grpc
  selector:
    app: customers-app-deployment