apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: customers-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: customers-app-deployment
    spec:
      containers:
        - name: customers-app-container
          image: rso6315/customers-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://customers-db.e-store:5432/customers
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customers-db-pass
                  key: POSTGRES_PASSWORD
            - name: KUMULUZEE_SECURITY_KEYCLOAK_CLIENT-SECRET
              valueFrom:
                secretKeyRef:
                  name: customers-app-pass
                  key: KUMULUZEE_SECURITY_KEYCLOAK_CLIENT-SECRET
#          readinessProbe:
#            httpGet:
#              path: /health/live
#              port: 8082
#              httpHeaders:
#                - name: Custom-Header
#                  value: Awesome
#            initialDelaySeconds: 3
#            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31010
  selector:
    app: customers-service